import {
  MdFastfood,
  MdLocalDrink,
  MdCake,
  MdDirectionsCar,
  MdCommute,
  MdSportsSoccer,
  MdGames,
  MdMusicNote,
  MdFlight,
  MdShoppingBag,
  MdHome,
  MdBook,
  MdSchool,
  MdElectricBolt,
  MdCardGiftcard,
  MdVolunteerActivism,
  MdAttachMoney,
  MdWork,
  MdRedeem,
  MdSavings,
  MdEmojiEvents,
} from "react-icons/md";

export const iconMap = {
  food: MdFastfood,
  drinks: MdLocalDrink,
  dessert: MdCake,
  snack: MdCake,
  taxi: MdDirectionsCar,
  longdistance: MdFlight,
  transport: MdCommute,
  bodybuilding: MdSportsSoccer,
  game: MdGames,
  audio: MdMusicNote,
  travel: MdFlight,
  clothes: MdShoppingBag,
  bag: MdShoppingBag,
  book: MdBook,
  promote: MdSchool,
  home: MdHome,
  shopping: MdShoppingBag,
  utilities: MdElectricBolt,
  gift: MdCardGiftcard,
  community: MdVolunteerActivism,

  salary: MdAttachMoney,
  overtimepay: MdWork,
  bonus: MdEmojiEvents,
  freelance: MdWork,
  financial: MdSavings,
  cashgift: MdCardGiftcard,
  rebate: MdRedeem,
};
